This is an Org-mode test file
* Spacemacs & Git
Do not use Git for frequent changes /Just divergent ones/
** Git
I have started using Git (via Magit), and now I still don't have good grips on
it, but I will store my notes in it.
*** Magit in Spacemacs   
I uncommented a git section in .spacemacs config file, and started using it
through magit commands (spc - spc - maggit-stuff). Use ctrl-c-ctrl-c to commit
when writing reasons for commit.
** Spacemacs
*** Themes
I'm currently using themes from
https://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bthemes/themes-megapackhttps://github.com/syl20bnr/spacemacs/tree/master/layers/%2Bthemes/themes-megapack
You can choose themes with spc-T-s.
/Themes affect line numbers/
*** Indirect Buffer
Refer to https://orgmode.org/manual/Global-and-local-cycling.html for indirect buffers (indirect buffer is , b in spacemacs).
Look in https://www.youtube.com/watch?v=VOfSjLwQY28 for examples. Resize by Ctrl-x + { (left) } (right), preceded by number to resize window - (see https://www.emacswiki.org/emacs/WindowResize).
*** Quick notes and logging
https://www.youtube.com/watch?v=nUvdddKZQzs&list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE&index=9
You can setup drawers to store your notes in.
*** Line wrapping
(See https://www.emacswiki.org/emacs/VisualLineMode)
It's called visual-line-mode.
You can add (setq line-move-visual nil) to wherever spacemacs needs (usually in .emacs). 
** Vim/GVim
Write org-mode in GVim. I don't know if this helps.
Try a Vim distribution /w org mode.
** Wishlist
+ How do I add neccesary commands to startup files in EMACS?
+ Treemacs (file explorer)
+ Persistent scratchpad (tab spc)
+ Discord and IRC for emax
+ Git Time Machine to switch between commits
+ Change font to calibri in config
+ Undo tree (use command undo-tree-auto-save-history to save undo history)
** Useful tips
   :LOGBOOK:
   - Note taken on [2018-11-27 otrd. 01:09] \\
     this is a test note
   :END:
- Add links to different headlines with [[ and closing double brackets.
- Toggle-frame-fullscreen (f11) to toggle fullscreen.
- Learn emacs commands for text manipulation in insert mode
- , R for Refile to different heading
- C-c C-z for a quick note, see [[Quick notes and logging]]
- Evil-org-mode keybindings  https://github.com/Somelauw/evil-org-mode
* League of Legends
  :LOGBOOK:
  - Note taken on [2018-12-04 otrd. 00:15] \\
    Riven - precharge q, to get passive and move and confuse
  - Note taken on [2018-12-03 pirmd. 22:11] \\
    Cho - Hextech belt to warmogs is dope, + armor and mr keystone
  - Note taken on [2018-11-30 piektd. 20:51] \\
    Xaya needs 3 quick attack rune, she bursty
  - Note taken on [2018-11-27 otrd. 01:26] \\
    AD tf does pitful damage, and a lot of it is still magic
  :END:
The first part is always trying to dart around (for energy) and observe the
situation (the intelectual part).
Kills, changes, action. Don't waste time on boring games. Plays, PLAYS, PLAAAAYS!!!
Do not stay put with weak ass, average performances. Want more. 
Do a chore before starting, it's good and increases performance.
* Music 
Singing. Need singing.
** Themes
I have found that I can seek wisdom from Queen's bicycle - fixate on one object,
center the theme around it.  Don't stay on the theme, but jump around it. Like
the lyric about the bicyle centers what you say.
** Trickses
Record acoustic songs and try to build from them.
* Motivation
Prepare for sleep - for now. Flux it, prepare.
/creative mutations are my infinte commitment. i define
all else through them/
Play guitar and sing everyday.
** Philosophy tidbits
You are what you do. Think, but bring it about.
You can't make everything clear, not yourself, not something else. [Kierkegaard, regarding an examined ethical life]
Allign the contradiction that is your mind (pride) and your body (despair)[Pascal]
What allows me to be (and to function and not perish) different is 
what will allow me to eat from the tree of exclusivity. [Me, the Grape-Liquifier]
** What I don't need
I don't need to add notes if I don't have good ideas. Let it go, in those cases, man.
** Slow days...
Capture nice little ways to fill the slowest of days.
- Writing your .org file is one way to fill a slow day
- Write specifically when Marta watches something interesting. Don't play, write.
- Researching emacs, vim and org is another way.
- Grow your [[Ledger of Quality]]
- Grow your [[Philosophy tidbits]]
- Practice using XKeymacs and Emacs keystrokes when writing (start /w movement keys and alts enabled)
- Take a zany not before sleep, but an hour before sleep!
* Customization
** Windows
- I have disabled Cpslck with KeyTweak and use caps lock to trigger XKeymacs
- Get 2 taskbars, hide 1? Get an alternative bar for battery, volume, etc.
** Linux
** Mac
** Vivaldi
Password is S with 123456
** The Ugly, the Useful and the Pretty
What constitutes functionaly and pretiness? What is the perfect ratio of these two parts?
- A minimal panel seems to be all I need
* Ledger of Quality
Not for simply enjoyable things, ONLY FOR SLIGHTLY-EXCEPTIONAL THINGS.
And maybe prone-to-being-forgetten things.
** Youtube
- SNL
- Interview with Hubert Dreyfus
** Reading
- Aeon 
- Wired Magazine
** Music
- Community of Hope: PJ Harvery
- Thundercat: Them Changes
** Subreddits
- CursedImages
- 4chan Mu
** Movies and TV shows
- BoJack Horseman
- The Ballad of Buster Scruggs
** Pics
https://www.reddit.com/r/adorableporn/comments/a00ryx/emily_bloom_uhd/
** Poets
- Jack Keroauc
* Raps & Poems
** Loser
** Vardle
I scrape my leftovers
To oblidge
What the man says
But not what the man means
* Archive
** Copied notes from VNote
*** Beggining
**** How do i write example notes?
 You start with paragraphs. Then you write, it's easy. Make a master lyrics file,
 then make a master note file that you share between devices. You might add a
 master poetry file, classify your thoughts.  Add links and pictures and just
 classify your thoughts! Discuss with yourself anything! And train to write! Your
 writing is... pedestrian.
**** I have succesfully started writing in ViM
 Use it. Markdown is now.
*** Motivation
**** Evenings
 Writing in the evenings is great way to gather whatever dirt you have dragged
 away with you. I have now written extra, just to practice writing.
**** When creative procceses move slow
 One tip is to create a free flowing musique-concrete-esque work. An older
 example is creating music without any regards to the stylistic, artistic or
 social value of if. In case of a freeze, create free-flowing work, experiment
 and care little or none at all.  Another thing to do is to try and force
 yourself and then take a walk and discuss the project at hand.
** New Horizons
 You have just begin using Org-mode. You may now track your thoughts in an
 organized manner!!!  This setup feels gorgeous! 
